// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  enum BumpSequenceResultCode
//  {
//      // codes considered as "success" for the operation
//      BUMP_SEQUENCE_SUCCESS = 0,
//      // codes considered as "failure" for the operation
//      BUMP_SEQUENCE_BAD_SEQ = -1 // `bumpTo` is not within bounds
//  };

//  ===========================================================================
public enum BumpSequenceResultCode implements XdrElement {
  BUMP_SEQUENCE_SUCCESS(0),
  BUMP_SEQUENCE_BAD_SEQ(-1),
  ;
  private final int mValue;

  BumpSequenceResultCode(int value) {
    mValue = value;
  }

  public static BumpSequenceResultCode decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static BumpSequenceResultCode decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return BUMP_SEQUENCE_SUCCESS;
      case -1:
        return BUMP_SEQUENCE_BAD_SEQ;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, BumpSequenceResultCode value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public int getValue() {
    return mValue;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }
}
