// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  enum ClaimableBalanceFlags
//  {
//      // If set, the issuer account of the asset held by the claimable balance may
//      // clawback the claimable balance
//      CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG = 0x1
//  };

//  ===========================================================================
public enum ClaimableBalanceFlags implements XdrElement {
  CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG(1),
  ;
  private int mValue;

  ClaimableBalanceFlags(int value) {
    mValue = value;
  }

  public int getValue() {
    return mValue;
  }

  public static ClaimableBalanceFlags decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static ClaimableBalanceFlags decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 1:
        return CLAIMABLE_BALANCE_CLAWBACK_ENABLED_FLAG;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, ClaimableBalanceFlags value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

}
