// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  union Claimant switch (ClaimantType type)
//  {
//  case CLAIMANT_TYPE_V0:
//      struct
//      {
//          AccountID destination;    // The account that can use this condition
//          ClaimPredicate predicate; // Claimable if predicate is true
//      } v0;
//  };

//  ===========================================================================
public class Claimant implements XdrElement {
  ClaimantType type;
  private ClaimantV0 v0;

  public Claimant() {
  }

  public static void encode(XdrDataOutputStream stream, Claimant encodedClaimant) throws IOException {
    //Xdrgen::AST::Identifier
    //ClaimantType
    stream.writeInt(encodedClaimant.getDiscriminant().getValue());
    switch (encodedClaimant.getDiscriminant()) {
      case CLAIMANT_TYPE_V0:
        ClaimantV0.encode(stream, encodedClaimant.v0);
        break;
    }
  }

  public static Claimant decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static Claimant decode(XdrDataInputStream stream) throws IOException {
    Claimant decodedClaimant = new Claimant();
    ClaimantType discriminant = ClaimantType.decode(stream);
    decodedClaimant.setDiscriminant(discriminant);
    switch (decodedClaimant.getDiscriminant()) {
      case CLAIMANT_TYPE_V0:
        decodedClaimant.v0 = ClaimantV0.decode(stream);
        break;
    }
    return decodedClaimant;
  }

  public ClaimantType getDiscriminant() {
    return this.type;
  }

  public void setDiscriminant(ClaimantType value) {
    this.type = value;
  }

  public ClaimantV0 getV0() {
    return this.v0;
  }

  public void setV0(ClaimantV0 value) {
    this.v0 = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.v0, this.type);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Claimant)) {
      return false;
    }

    Claimant other = (Claimant) object;
    return Objects.equal(this.v0, other.v0) && Objects.equal(this.type, other.type);
  }

  public static final class Builder {
    private ClaimantType discriminant;
    private ClaimantV0 v0;

    public Builder discriminant(ClaimantType discriminant) {
      this.discriminant = discriminant;
      return this;
    }

    public Builder v0(ClaimantV0 v0) {
      this.v0 = v0;
      return this;
    }

    public Claimant build() {
      Claimant val = new Claimant();
      val.setDiscriminant(discriminant);
      val.setV0(v0);
      return val;
    }
  }

  public static class ClaimantV0 {
    private AccountID destination;
    private ClaimPredicate predicate;

    public ClaimantV0() {
    }

    public static void encode(XdrDataOutputStream stream, ClaimantV0 encodedClaimantV0) throws IOException {
      AccountID.encode(stream, encodedClaimantV0.destination);
      ClaimPredicate.encode(stream, encodedClaimantV0.predicate);
    }

    public static ClaimantV0 decode(ByteString bs) throws IOException {
      return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
    }

    public static ClaimantV0 decode(XdrDataInputStream stream) throws IOException {
      ClaimantV0 decodedClaimantV0 = new ClaimantV0();
      decodedClaimantV0.destination = AccountID.decode(stream);
      decodedClaimantV0.predicate = ClaimPredicate.decode(stream);
      return decodedClaimantV0;
    }

    public AccountID getDestination() {
      return this.destination;
    }

    public void setDestination(AccountID value) {
      this.destination = value;
    }

    public ClaimPredicate getPredicate() {
      return this.predicate;
    }

    public void setPredicate(ClaimPredicate value) {
      this.predicate = value;
    }

    public void encode(XdrDataOutputStream stream) throws IOException {
      encode(stream, this);
    }

    public ByteString encode() throws IOException {
      ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
      XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
      encode(xdrOutputStream);
      return new ByteString(byteStream.toByteArray());
    }

    @Override
    public int hashCode() {
      return Objects.hashCode(this.destination, this.predicate);
    }

    @Override
    public boolean equals(Object object) {
      if (!(object instanceof ClaimantV0)) {
        return false;
      }

      ClaimantV0 other = (ClaimantV0) object;
      return Objects.equal(this.destination, other.destination) && Objects.equal(this.predicate, other.predicate);
    }

    public static final class Builder {
      private AccountID destination;
      private ClaimPredicate predicate;

      public Builder destination(AccountID destination) {
        this.destination = destination;
        return this;
      }

      public Builder predicate(ClaimPredicate predicate) {
        this.predicate = predicate;
        return this;
      }

      public ClaimantV0 build() {
        ClaimantV0 val = new ClaimantV0();
        val.setDestination(destination);
        val.setPredicate(predicate);
        return val;
      }
    }

  }
}
