// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  struct ClawbackClaimableBalanceOp
//  {
//      ClaimableBalanceID balanceID;
//  };

//  ===========================================================================
public class ClawbackClaimableBalanceOp implements XdrElement {
  private ClaimableBalanceID balanceID;

  public ClawbackClaimableBalanceOp() {
  }

  public static void encode(
      XdrDataOutputStream stream,
      ClawbackClaimableBalanceOp encodedClawbackClaimableBalanceOp
  ) throws IOException {
    ClaimableBalanceID.encode(stream, encodedClawbackClaimableBalanceOp.balanceID);
  }

  public static ClawbackClaimableBalanceOp decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static ClawbackClaimableBalanceOp decode(XdrDataInputStream stream) throws IOException {
    ClawbackClaimableBalanceOp decodedClawbackClaimableBalanceOp = new ClawbackClaimableBalanceOp();
    decodedClawbackClaimableBalanceOp.balanceID = ClaimableBalanceID.decode(stream);
    return decodedClawbackClaimableBalanceOp;
  }

  public ClaimableBalanceID getBalanceID() {
    return this.balanceID;
  }

  public void setBalanceID(ClaimableBalanceID value) {
    this.balanceID = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.balanceID);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof ClawbackClaimableBalanceOp)) {
      return false;
    }

    ClawbackClaimableBalanceOp other = (ClawbackClaimableBalanceOp) object;
    return Objects.equal(this.balanceID, other.balanceID);
  }

  public static final class Builder {
    private ClaimableBalanceID balanceID;

    public Builder balanceID(ClaimableBalanceID balanceID) {
      this.balanceID = balanceID;
      return this;
    }

    public ClawbackClaimableBalanceOp build() {
      ClawbackClaimableBalanceOp val = new ClawbackClaimableBalanceOp();
      val.setBalanceID(balanceID);
      return val;
    }
  }
}
