// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  struct ClawbackOp
//  {
//      Asset asset;
//      MuxedAccount from;
//      int64 amount;
//  };

//  ===========================================================================
public class ClawbackOp implements XdrElement {
  private Asset asset;
  private MuxedAccount from;
  private Int64 amount;

  public ClawbackOp() {
  }

  public static void encode(XdrDataOutputStream stream, ClawbackOp encodedClawbackOp) throws IOException {
    Asset.encode(stream, encodedClawbackOp.asset);
    MuxedAccount.encode(stream, encodedClawbackOp.from);
    Int64.encode(stream, encodedClawbackOp.amount);
  }

  public static ClawbackOp decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static ClawbackOp decode(XdrDataInputStream stream) throws IOException {
    ClawbackOp decodedClawbackOp = new ClawbackOp();
    decodedClawbackOp.asset = Asset.decode(stream);
    decodedClawbackOp.from = MuxedAccount.decode(stream);
    decodedClawbackOp.amount = Int64.decode(stream);
    return decodedClawbackOp;
  }

  public Asset getAsset() {
    return this.asset;
  }

  public void setAsset(Asset value) {
    this.asset = value;
  }

  public MuxedAccount getFrom() {
    return this.from;
  }

  public void setFrom(MuxedAccount value) {
    this.from = value;
  }

  public Int64 getAmount() {
    return this.amount;
  }

  public void setAmount(Int64 value) {
    this.amount = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.asset, this.from, this.amount);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof ClawbackOp)) {
      return false;
    }

    ClawbackOp other = (ClawbackOp) object;
    return Objects.equal(this.asset, other.asset) && Objects.equal(this.from, other.from) && Objects
        .equal(this.amount, other.amount);
  }

  public static final class Builder {
    private Asset asset;
    private MuxedAccount from;
    private Int64 amount;

    public Builder asset(Asset asset) {
      this.asset = asset;
      return this;
    }

    public Builder from(MuxedAccount from) {
      this.from = from;
      return this;
    }

    public Builder amount(Int64 amount) {
      this.amount = amount;
      return this;
    }

    public ClawbackOp build() {
      ClawbackOp val = new ClawbackOp();
      val.setAsset(asset);
      val.setFrom(from);
      val.setAmount(amount);
      return val;
    }
  }
}
