// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Arrays;
import okio.ByteString;

// === xdr source ============================================================

//  typedef opaque DataValue<64>;

//  ===========================================================================
public class DataValue implements XdrElement {
  private byte[] DataValue;

  public static void encode(XdrDataOutputStream stream, DataValue encodedDataValue) throws IOException {
    int DataValuesize = encodedDataValue.DataValue.length;
    stream.writeInt(DataValuesize);
    stream.write(encodedDataValue.getDataValue(), 0, DataValuesize);
  }

  public static DataValue decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static DataValue decode(XdrDataInputStream stream) throws IOException {
    DataValue decodedDataValue = new DataValue();
    int DataValuesize = stream.readInt();
    decodedDataValue.DataValue = new byte[DataValuesize];
    stream.read(decodedDataValue.DataValue, 0, DataValuesize);
    return decodedDataValue;
  }

  public byte[] getDataValue() {
    return this.DataValue;
  }

  public void setDataValue(byte[] value) {
    this.DataValue = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Arrays.hashCode(this.DataValue);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof DataValue)) {
      return false;
    }

    DataValue other = (DataValue) object;
    return Arrays.equals(this.DataValue, other.DataValue);
  }
}
