// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  typedef hyper int64;

//  ===========================================================================
public class Int64 implements XdrElement {
  private Long int64;

  public static void encode(XdrDataOutputStream stream, Int64 encodedInt64) throws IOException {
    stream.writeLong(encodedInt64.int64);
  }

  public static Int64 decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static Int64 decode(XdrDataInputStream stream) throws IOException {
    Int64 decodedInt64 = new Int64();
    decodedInt64.int64 = stream.readLong();
    return decodedInt64;
  }

  public Long getInt64() {
    return this.int64;
  }

  public void setInt64(Long value) {
    this.int64 = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.int64);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof Int64)) {
      return false;
    }

    Int64 other = (Int64) object;
    return Objects.equal(this.int64, other.int64);
  }
}
