// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  struct LedgerEntryExtensionV1
//  {
//      SponsorshipDescriptor sponsoringID;
//
//      union switch (int v)
//      {
//      case 0:
//          void;
//      }
//      ext;
//  };

//  ===========================================================================
public class LedgerEntryExtensionV1 implements XdrElement {
  private SponsorshipDescriptor sponsoringID;
  private LedgerEntryExtensionV1Ext ext;

  public LedgerEntryExtensionV1() {
  }

  public static void encode(XdrDataOutputStream stream, LedgerEntryExtensionV1 encodedLedgerEntryExtensionV1)
      throws IOException {
    SponsorshipDescriptor.encode(stream, encodedLedgerEntryExtensionV1.sponsoringID);
    LedgerEntryExtensionV1Ext.encode(stream, encodedLedgerEntryExtensionV1.ext);
  }

  public static LedgerEntryExtensionV1 decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static LedgerEntryExtensionV1 decode(XdrDataInputStream stream) throws IOException {
    LedgerEntryExtensionV1 decodedLedgerEntryExtensionV1 = new LedgerEntryExtensionV1();
    decodedLedgerEntryExtensionV1.sponsoringID = SponsorshipDescriptor.decode(stream);
    decodedLedgerEntryExtensionV1.ext = LedgerEntryExtensionV1Ext.decode(stream);
    return decodedLedgerEntryExtensionV1;
  }

  public SponsorshipDescriptor getSponsoringID() {
    return this.sponsoringID;
  }

  public void setSponsoringID(SponsorshipDescriptor value) {
    this.sponsoringID = value;
  }

  public LedgerEntryExtensionV1Ext getExt() {
    return this.ext;
  }

  public void setExt(LedgerEntryExtensionV1Ext value) {
    this.ext = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.sponsoringID, this.ext);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof LedgerEntryExtensionV1)) {
      return false;
    }

    LedgerEntryExtensionV1 other = (LedgerEntryExtensionV1) object;
    return Objects.equal(this.sponsoringID, other.sponsoringID) && Objects.equal(this.ext, other.ext);
  }

  public static final class Builder {
    private SponsorshipDescriptor sponsoringID;
    private LedgerEntryExtensionV1Ext ext;

    public Builder sponsoringID(SponsorshipDescriptor sponsoringID) {
      this.sponsoringID = sponsoringID;
      return this;
    }

    public Builder ext(LedgerEntryExtensionV1Ext ext) {
      this.ext = ext;
      return this;
    }

    public LedgerEntryExtensionV1 build() {
      LedgerEntryExtensionV1 val = new LedgerEntryExtensionV1();
      val.setSponsoringID(sponsoringID);
      val.setExt(ext);
      return val;
    }
  }

  public static class LedgerEntryExtensionV1Ext {
    Integer v;

    public LedgerEntryExtensionV1Ext() {
    }

    public static void encode(XdrDataOutputStream stream, LedgerEntryExtensionV1Ext encodedLedgerEntryExtensionV1Ext)
        throws IOException {
      //Xdrgen::AST::Typespecs::Int
      //Integer
      stream.writeInt(encodedLedgerEntryExtensionV1Ext.getDiscriminant().intValue());
      switch (encodedLedgerEntryExtensionV1Ext.getDiscriminant()) {
        case 0:
          break;
      }
    }

    public static LedgerEntryExtensionV1Ext decode(ByteString bs) throws IOException {
      return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
    }

    public static LedgerEntryExtensionV1Ext decode(XdrDataInputStream stream) throws IOException {
      LedgerEntryExtensionV1Ext decodedLedgerEntryExtensionV1Ext = new LedgerEntryExtensionV1Ext();
      Integer discriminant = stream.readInt();
      decodedLedgerEntryExtensionV1Ext.setDiscriminant(discriminant);
      switch (decodedLedgerEntryExtensionV1Ext.getDiscriminant()) {
        case 0:
          break;
      }
      return decodedLedgerEntryExtensionV1Ext;
    }

    public Integer getDiscriminant() {
      return this.v;
    }

    public void setDiscriminant(Integer value) {
      this.v = value;
    }

    public void encode(XdrDataOutputStream stream) throws IOException {
      encode(stream, this);
    }

    public ByteString encode() throws IOException {
      ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
      XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
      encode(xdrOutputStream);
      return new ByteString(byteStream.toByteArray());
    }

    @Override
    public int hashCode() {
      return Objects.hashCode(this.v);
    }

    @Override
    public boolean equals(Object object) {
      if (!(object instanceof LedgerEntryExtensionV1Ext)) {
        return false;
      }

      LedgerEntryExtensionV1Ext other = (LedgerEntryExtensionV1Ext) object;
      return Objects.equal(this.v, other.v);
    }

    public static final class Builder {
      private Integer discriminant;

      public Builder discriminant(Integer discriminant) {
        this.discriminant = discriminant;
        return this;
      }

      public LedgerEntryExtensionV1Ext build() {
        LedgerEntryExtensionV1Ext val = new LedgerEntryExtensionV1Ext();
        val.setDiscriminant(discriminant);
        return val;
      }
    }
  }
}
