// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  struct Liabilities
//  {
//      int64 buying;
//      int64 selling;
//  };

//  ===========================================================================
public class Liabilities implements XdrElement {
  private Int64 buying;
  private Int64 selling;

  public Liabilities() {
  }

  public static void encode(XdrDataOutputStream stream, Liabilities encodedLiabilities) throws IOException {
    Int64.encode(stream, encodedLiabilities.buying);
    Int64.encode(stream, encodedLiabilities.selling);
  }

  public static Liabilities decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static Liabilities decode(XdrDataInputStream stream) throws IOException {
    Liabilities decodedLiabilities = new Liabilities();
    decodedLiabilities.buying = Int64.decode(stream);
    decodedLiabilities.selling = Int64.decode(stream);
    return decodedLiabilities;
  }

  public Int64 getBuying() {
    return this.buying;
  }

  public void setBuying(Int64 value) {
    this.buying = value;
  }

  public Int64 getSelling() {
    return this.selling;
  }

  public void setSelling(Int64 value) {
    this.selling = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.buying, this.selling);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof Liabilities)) {
      return false;
    }

    Liabilities other = (Liabilities) object;
    return Objects.equal(this.buying, other.buying) && Objects.equal(this.selling, other.selling);
  }
}
