// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;


import java.io.IOException;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import okio.ByteString;

// === xdr source ============================================================

//  enum LiquidityPoolType
//  {
//      LIQUIDITY_POOL_CONSTANT_PRODUCT = 0
//  };

//  ===========================================================================
public enum LiquidityPoolType implements XdrElement {
  LIQUIDITY_POOL_CONSTANT_PRODUCT(0),
  ;
  private int mValue;

  LiquidityPoolType(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  public static LiquidityPoolType decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static LiquidityPoolType decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0: return LIQUIDITY_POOL_CONSTANT_PRODUCT;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, LiquidityPoolType value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

}
