// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.IOException;

// === xdr source ============================================================

//  struct OperationMeta
//  {
//      LedgerEntryChanges changes;
//  };

//  ===========================================================================
public class OperationMeta implements XdrElement {
  private LedgerEntryChanges changes;

  public OperationMeta() {
  }

  public static void encode(XdrDataOutputStream stream, OperationMeta encodedOperationMeta) throws IOException {
    LedgerEntryChanges.encode(stream, encodedOperationMeta.changes);
  }

  public static OperationMeta decode(XdrDataInputStream stream) throws IOException {
    OperationMeta decodedOperationMeta = new OperationMeta();
    decodedOperationMeta.changes = LedgerEntryChanges.decode(stream);
    return decodedOperationMeta;
  }

  public LedgerEntryChanges getChanges() {
    return this.changes;
  }

  public void setChanges(LedgerEntryChanges value) {
    this.changes = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.changes);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof OperationMeta)) {
      return false;
    }

    OperationMeta other = (OperationMeta) object;
    return Objects.equal(this.changes, other.changes);
  }
}
