// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  enum RevokeSponsorshipResultCode
//  {
//      // codes considered as "success" for the operation
//      REVOKE_SPONSORSHIP_SUCCESS = 0,
//
//      // codes considered as "failure" for the operation
//      REVOKE_SPONSORSHIP_DOES_NOT_EXIST = -1,
//      REVOKE_SPONSORSHIP_NOT_SPONSOR = -2,
//      REVOKE_SPONSORSHIP_LOW_RESERVE = -3,
//      REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE = -4
//  };

//  ===========================================================================
public enum RevokeSponsorshipResultCode implements XdrElement {
  REVOKE_SPONSORSHIP_SUCCESS(0),
  REVOKE_SPONSORSHIP_DOES_NOT_EXIST(-1),
  REVOKE_SPONSORSHIP_NOT_SPONSOR(-2),
  REVOKE_SPONSORSHIP_LOW_RESERVE(-3),
  REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE(-4),
  ;
  private final int mValue;

  RevokeSponsorshipResultCode(int value) {
    mValue = value;
  }

  public static RevokeSponsorshipResultCode decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static RevokeSponsorshipResultCode decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0:
        return REVOKE_SPONSORSHIP_SUCCESS;
      case -1:
        return REVOKE_SPONSORSHIP_DOES_NOT_EXIST;
      case -2:
        return REVOKE_SPONSORSHIP_NOT_SPONSOR;
      case -3:
        return REVOKE_SPONSORSHIP_LOW_RESERVE;
      case -4:
        return REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, RevokeSponsorshipResultCode value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public int getValue() {
    return mValue;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }
}
