// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  union SetTrustLineFlagsResult switch (SetTrustLineFlagsResultCode code)
//  {
//  case SET_TRUST_LINE_FLAGS_SUCCESS:
//      void;
//  default:
//      void;
//  };

//  ===========================================================================
public class SetTrustLineFlagsResult implements XdrElement {
  SetTrustLineFlagsResultCode code;

  public SetTrustLineFlagsResult() {
  }

  public static void encode(
      XdrDataOutputStream stream,
      SetTrustLineFlagsResult encodedSetTrustLineFlagsResult
  ) throws IOException {
    //Xdrgen::AST::Identifier
    //SetTrustLineFlagsResultCode
    stream.writeInt(encodedSetTrustLineFlagsResult.getDiscriminant().getValue());
    switch (encodedSetTrustLineFlagsResult.getDiscriminant()) {
      case SET_TRUST_LINE_FLAGS_SUCCESS:
        break;
      default:
        break;
    }
  }

  public static SetTrustLineFlagsResult decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static SetTrustLineFlagsResult decode(XdrDataInputStream stream) throws IOException {
    SetTrustLineFlagsResult decodedSetTrustLineFlagsResult = new SetTrustLineFlagsResult();
    SetTrustLineFlagsResultCode discriminant = SetTrustLineFlagsResultCode.decode(stream);
    decodedSetTrustLineFlagsResult.setDiscriminant(discriminant);
    switch (decodedSetTrustLineFlagsResult.getDiscriminant()) {
      case SET_TRUST_LINE_FLAGS_SUCCESS:
        break;
      default:
        break;
    }
    return decodedSetTrustLineFlagsResult;
  }

  public SetTrustLineFlagsResultCode getDiscriminant() {
    return this.code;
  }

  public void setDiscriminant(SetTrustLineFlagsResultCode value) {
    this.code = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.code);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof SetTrustLineFlagsResult)) {
      return false;
    }

    SetTrustLineFlagsResult other = (SetTrustLineFlagsResult) object;
    return Objects.equal(this.code, other.code);
  }

  public static final class Builder {
    private SetTrustLineFlagsResultCode discriminant;

    public Builder discriminant(SetTrustLineFlagsResultCode discriminant) {
      this.discriminant = discriminant;
      return this;
    }

    public SetTrustLineFlagsResult build() {
      SetTrustLineFlagsResult val = new SetTrustLineFlagsResult();
      val.setDiscriminant(discriminant);
      return val;
    }
  }
}
