// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.IOException;

// === xdr source ============================================================

//  struct SignedSurveyResponseMessage
//  {
//      Signature responseSignature;
//      SurveyResponseMessage response;
//  };

//  ===========================================================================
public class SignedSurveyResponseMessage implements XdrElement {
  private Signature responseSignature;
  private SurveyResponseMessage response;

  public SignedSurveyResponseMessage() {
  }

  public static void encode(XdrDataOutputStream stream, SignedSurveyResponseMessage encodedSignedSurveyResponseMessage)
      throws IOException {
    Signature.encode(stream, encodedSignedSurveyResponseMessage.responseSignature);
    SurveyResponseMessage.encode(stream, encodedSignedSurveyResponseMessage.response);
  }

  public static SignedSurveyResponseMessage decode(XdrDataInputStream stream) throws IOException {
    SignedSurveyResponseMessage decodedSignedSurveyResponseMessage = new SignedSurveyResponseMessage();
    decodedSignedSurveyResponseMessage.responseSignature = Signature.decode(stream);
    decodedSignedSurveyResponseMessage.response = SurveyResponseMessage.decode(stream);
    return decodedSignedSurveyResponseMessage;
  }

  public Signature getResponseSignature() {
    return this.responseSignature;
  }

  public void setResponseSignature(Signature value) {
    this.responseSignature = value;
  }

  public SurveyResponseMessage getResponse() {
    return this.response;
  }

  public void setResponse(SurveyResponseMessage value) {
    this.response = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.responseSignature, this.response);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof SignedSurveyResponseMessage)) {
      return false;
    }

    SignedSurveyResponseMessage other = (SignedSurveyResponseMessage) object;
    return Objects.equal(this.responseSignature, other.responseSignature) && Objects.equal(this.response,
        other.response);
  }
}
