// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  struct Signer
//  {
//      SignerKey key;
//      uint32 weight; // really only need 1 byte
//  };

//  ===========================================================================
public class Signer implements XdrElement {
  private SignerKey key;
  private Uint32 weight;

  public Signer() {
  }

  public static void encode(XdrDataOutputStream stream, Signer encodedSigner) throws IOException {
    SignerKey.encode(stream, encodedSigner.key);
    Uint32.encode(stream, encodedSigner.weight);
  }

  public static Signer decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static Signer decode(XdrDataInputStream stream) throws IOException {
    Signer decodedSigner = new Signer();
    decodedSigner.key = SignerKey.decode(stream);
    decodedSigner.weight = Uint32.decode(stream);
    return decodedSigner;
  }

  public SignerKey getKey() {
    return this.key;
  }

  public void setKey(SignerKey value) {
    this.key = value;
  }

  public Uint32 getWeight() {
    return this.weight;
  }

  public void setWeight(Uint32 value) {
    this.weight = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.key, this.weight);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof Signer)) {
      return false;
    }

    Signer other = (Signer) object;
    return Objects.equal(this.key, other.key) && Objects.equal(this.weight, other.weight);
  }
}
