// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  union SurveyResponseBody switch (SurveyMessageCommandType type)
//  {
//  case SURVEY_TOPOLOGY:
//      TopologyResponseBody topologyResponseBody;
//  };

//  ===========================================================================
public class SurveyResponseBody implements XdrElement {
  SurveyMessageCommandType type;
  private TopologyResponseBody topologyResponseBody;

  public SurveyResponseBody() {
  }

  public static void encode(
      XdrDataOutputStream stream,
      SurveyResponseBody encodedSurveyResponseBody
  ) throws IOException {
    //Xdrgen::AST::Identifier
    //SurveyMessageCommandType
    stream.writeInt(encodedSurveyResponseBody.getDiscriminant().getValue());
    switch (encodedSurveyResponseBody.getDiscriminant()) {
      case SURVEY_TOPOLOGY:
        TopologyResponseBody.encode(stream, encodedSurveyResponseBody.topologyResponseBody);
        break;
    }
  }

  public static SurveyResponseBody decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static SurveyResponseBody decode(XdrDataInputStream stream) throws IOException {
    SurveyResponseBody decodedSurveyResponseBody = new SurveyResponseBody();
    SurveyMessageCommandType discriminant = SurveyMessageCommandType.decode(stream);
    decodedSurveyResponseBody.setDiscriminant(discriminant);
    switch (decodedSurveyResponseBody.getDiscriminant()) {
      case SURVEY_TOPOLOGY:
        decodedSurveyResponseBody.topologyResponseBody = TopologyResponseBody.decode(stream);
        break;
    }
    return decodedSurveyResponseBody;
  }

  public SurveyMessageCommandType getDiscriminant() {
    return this.type;
  }

  public void setDiscriminant(SurveyMessageCommandType value) {
    this.type = value;
  }

  public TopologyResponseBody getTopologyResponseBody() {
    return this.topologyResponseBody;
  }

  public void setTopologyResponseBody(TopologyResponseBody value) {
    this.topologyResponseBody = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.topologyResponseBody, this.type);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof SurveyResponseBody)) {
      return false;
    }

    SurveyResponseBody other = (SurveyResponseBody) object;
    return Objects.equal(this.topologyResponseBody, other.topologyResponseBody) && Objects.equal(this.type, other.type);
  }

  public static final class Builder {
    private SurveyMessageCommandType discriminant;
    private TopologyResponseBody topologyResponseBody;

    public Builder discriminant(SurveyMessageCommandType discriminant) {
      this.discriminant = discriminant;
      return this;
    }

    public Builder topologyResponseBody(TopologyResponseBody topologyResponseBody) {
      this.topologyResponseBody = topologyResponseBody;
      return this;
    }

    public SurveyResponseBody build() {
      SurveyResponseBody val = new SurveyResponseBody();
      val.setDiscriminant(discriminant);
      val.setTopologyResponseBody(topologyResponseBody);
      return val;
    }
  }
}
