// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  typedef uint64 TimePoint;

//  ===========================================================================
public class TimePoint implements XdrElement {
  private Uint64 TimePoint;

  public TimePoint() {
  }

  public TimePoint(Uint64 TimePoint) {
    this.TimePoint = TimePoint;
  }

  public Uint64 getTimePoint() {
    return this.TimePoint;
  }

  public void setTimePoint(Uint64 value) {
    this.TimePoint = value;
  }

  public static void encode(XdrDataOutputStream stream, TimePoint encodedTimePoint) throws IOException {
    Uint64.encode(stream, encodedTimePoint.TimePoint);
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  public static TimePoint decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static TimePoint decode(XdrDataInputStream stream) throws IOException {
    TimePoint decodedTimePoint = new TimePoint();
    decodedTimePoint.TimePoint = Uint64.decode(stream);
    return decodedTimePoint;
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.TimePoint);
  }

  @Override
  public boolean equals(Object object) {
    if (!(object instanceof TimePoint)) {
      return false;
    }

    TimePoint other = (TimePoint) object;
    return Objects.equal(this.TimePoint, other.TimePoint);
  }
}
