// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.IOException;

// === xdr source ============================================================

//  struct TransactionResultPair
//  {
//      Hash transactionHash;
//      TransactionResult result; // result for the transaction
//  };

//  ===========================================================================
public class TransactionResultPair implements XdrElement {
  private Hash transactionHash;
  private TransactionResult result;

  public TransactionResultPair() {
  }

  public static void encode(XdrDataOutputStream stream, TransactionResultPair encodedTransactionResultPair)
      throws IOException {
    Hash.encode(stream, encodedTransactionResultPair.transactionHash);
    TransactionResult.encode(stream, encodedTransactionResultPair.result);
  }

  public static TransactionResultPair decode(XdrDataInputStream stream) throws IOException {
    TransactionResultPair decodedTransactionResultPair = new TransactionResultPair();
    decodedTransactionResultPair.transactionHash = Hash.decode(stream);
    decodedTransactionResultPair.result = TransactionResult.decode(stream);
    return decodedTransactionResultPair;
  }

  public Hash getTransactionHash() {
    return this.transactionHash;
  }

  public void setTransactionHash(Hash value) {
    this.transactionHash = value;
  }

  public TransactionResult getResult() {
    return this.result;
  }

  public void setResult(TransactionResult value) {
    this.result = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.transactionHash, this.result);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof TransactionResultPair)) {
      return false;
    }

    TransactionResultPair other = (TransactionResultPair) object;
    return Objects.equal(this.transactionHash, other.transactionHash) && Objects.equal(this.result, other.result);
  }
}
