// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package org.stellar.xdr;

import com.google.common.base.Objects;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import okio.ByteString;

// === xdr source ============================================================

//  typedef unsigned hyper uint64;

//  ===========================================================================
public class Uint64 implements XdrElement {
  private Long uint64;

  public static void encode(XdrDataOutputStream stream, Uint64 encodedUint64) throws IOException {
    stream.writeLong(encodedUint64.uint64);
  }

  public static Uint64 decode(ByteString bs) throws IOException {
    return decode(new XdrDataInputStream(new ByteArrayInputStream(bs.toByteArray())));
  }

  public static Uint64 decode(XdrDataInputStream stream) throws IOException {
    Uint64 decodedUint64 = new Uint64();
    decodedUint64.uint64 = stream.readLong();
    return decodedUint64;
  }

  public Long getUint64() {
    return this.uint64;
  }

  public void setUint64(Long value) {
    this.uint64 = value;
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }

  public ByteString encode() throws IOException {
    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
    XdrDataOutputStream xdrOutputStream = new XdrDataOutputStream(byteStream);
    encode(xdrOutputStream);
    return new ByteString(byteStream.toByteArray());
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(this.uint64);
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || !(object instanceof Uint64)) {
      return false;
    }

    Uint64 other = (Uint64) object;
    return Objects.equal(this.uint64, other.uint64);
  }
}
